sonar.host.url=http://35.200.183.81:9000
sonar.token=YOUR_TOKEN

sonar.projectKey=gdna-aeos
sonar.projectName=gdna-aeos

sonar.sources=.
sonar.tests=.

sonar.exclusions=node_modules/**,dist/**,build/**,.scannerwork/**

sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts