'use strict';

const fs = require('fs-extra');
const path = require('path');
const { logInfo, logSuccess } = require('./logger');
const { installDevDependency } = require('./packageManager');

const SONAR_PROPS_FILE = 'sonar-project.properties';
const DEFAULT_SONAR_HOST = process.env.SONAR_HOST_URL || 'http://localhost:9000';
const DEFAULT_SONAR_TOKEN = process.env.SONAR_TOKEN || '';
const TOKEN_PLACEHOLDER = 'REPLACE_WITH_YOUR_TOKEN';

// ─────────────────────────────────────────────────────────────
// CREATE SONAR PROJECT
// ─────────────────────────────────────────────────────────────
async function ensureProjectExists(projectKey, projectName, hostUrl, token) {
  if (!token || token === TOKEN_PLACEHOLDER) {
    logInfo('SONAR_TOKEN not set — skipping project creation.');
    return;
  }

  let parsedHost;
  try {
    parsedHost = new URL(hostUrl);
  } catch {
    logInfo(`Invalid SonarQube URL "${hostUrl}" — skipping.`);
    return;
  }

  const http = parsedHost.protocol === 'https:' ? require('https') : require('http');
  const auth = Buffer.from(`${token}:`).toString('base64');
  const postData = `name=${encodeURIComponent(projectName)}&project=${encodeURIComponent(projectKey)}`;

  return new Promise((resolve) => {
    const req = http.request({
      hostname: parsedHost.hostname,
      port: parsedHost.port || (parsedHost.protocol === 'https:' ? 443 : 80),
      path: '/api/projects/create',
      method: 'POST',
      headers: {
        Authorization: `Basic ${auth}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': Buffer.byteLength(postData),
      }
    }, (res) => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        if ([200, 201].includes(res.statusCode)) {
          logSuccess(`Project "${projectKey}" created.`);
        } else if (data.includes('already exists')) {
          logInfo(`Project "${projectKey}" already exists.`);
        }
        resolve();
      });
    });

    req.on('error', () => resolve());
    req.write(postData);
    req.end();
  });
}

// ─────────────────────────────────────────────────────────────
// INSTALL SCANNER
// ─────────────────────────────────────────────────────────────
exports.installSonarScanner = async () => {
  logInfo('Installing sonarqube-scanner...');
  await installDevDependency('sonarqube-scanner');
  logSuccess('sonarqube-scanner installed.');
};

// ─────────────────────────────────────────────────────────────
// DETECT TEST STRUCTURE
// ─────────────────────────────────────────────────────────────
function detectTestConfig() {
  const cwd = process.cwd();

  const possibleTestDirs = ['tests', '__tests__', 'test'];
  const existingTestDirs = possibleTestDirs.filter(dir =>
    fs.existsSync(path.join(cwd, dir))
  );

  // If test folders exist → use them directly
  if (existingTestDirs.length > 0) {
    return {
      testsLine: `sonar.tests=${existingTestDirs.join(',')}`,
      inclusionsLine: ''
    };
  }

  // Otherwise fallback to pattern-based detection
  return {
    testsLine: `sonar.tests=.`,
    inclusionsLine: `sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts`
  };
}

// ─────────────────────────────────────────────────────────────
// MAIN SETUP FUNCTION
// ─────────────────────────────────────────────────────────────
exports.setupSonarProperties = async () => {
  const propsPath = path.join(process.cwd(), SONAR_PROPS_FILE);

  let projectKey = 'my-project';
  let projectName = 'My Project';

  const pkgPath = path.join(process.cwd(), 'package.json');
  if (await fs.pathExists(pkgPath)) {
    const pkg = await fs.readJSON(pkgPath);
    if (pkg.name) {
      projectKey = pkg.name.replace(/[^a-zA-Z0-9_\-.:]/g, '_');
      projectName = pkg.name;
    }
  }

  // STEP 1: Create project in SonarQube
  await ensureProjectExists(
    projectKey,
    projectName,
    DEFAULT_SONAR_HOST,
    DEFAULT_SONAR_TOKEN
  );

  // STEP 2: Detect test setup
  const { testsLine, inclusionsLine } = detectTestConfig();

  // STEP 3: Write sonar-project.properties
  // Ensure sonar.sources and sonar.tests are DISJOINT to prevent "File indexed twice" error.
  // sonar.sources must explicitly exclude test directories.
  const testDirsForExclusion = ['tests', '__tests__', 'test', '__test__', 'spec', '__specs__'];
  const existingTestDirs = testDirsForExclusion.filter(dir =>
    fs.existsSync(path.join(process.cwd(), dir))
  );

  const testExclusionPatterns = existingTestDirs.map(d => `${d}/**`).join(',');
  const sourceExclusions = [
    'node_modules/**', 'dist/**', 'build/**', '.scannerwork/**',
    '**/*.test.js', '**/*.test.ts', '**/*.test.tsx', '**/*.test.jsx',
    '**/*.spec.js', '**/*.spec.ts', '**/*.spec.tsx', '**/*.spec.jsx',
    ...(testExclusionPatterns ? [testExclusionPatterns] : [])
  ].join(',');

  const content = `# Auto-generated by cs-setup

sonar.host.url=${DEFAULT_SONAR_HOST}
sonar.token=${DEFAULT_SONAR_TOKEN || TOKEN_PLACEHOLDER}

sonar.projectKey=${projectKey}
sonar.projectName=${projectName}

# Sources — explicitly excludes test files/dirs to prevent "File indexed twice"
sonar.sources=.
sonar.exclusions=${sourceExclusions}

# Tests — separate from sources (disjoint paths required by SonarQube)
${testsLine}
${inclusionsLine ? inclusionsLine : ''}

# Coverage report path (generated by Jest/Vitest before sonar scan)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
`;

  await fs.writeFile(propsPath, content.trim() + '\n');

  logSuccess(`Created ${propsPath}`);
};